### ISSUE TITLE
Copy previous months location information

### ISSUE THREAD

**Issue by civrot** [PuzzledPint/puzzledpint.com#57]
Allow location GC to copy values from previous events.

**Comment by mcleinman** [comment]
Sorry to be late to this one.  Does this copy when you press a button, or auto-fill when a month is created?  If the latter, we don't have visibility for cities that flake and haven't updated/approved their location...

**Comment by BrianEnigma** [comment]
I don't have it set up on this laptop to offer up a screenshot, but on the location edit page for a given city, at the bottom, it lists the three most recent locations. Each has a “Copy” button next to it. Clicking on the button fills+saves the month's location with that corresponding previous month's info.

**Comment by mcleinman** [comment]
Perfect.  Sounds awesome.  Thank you!

**Comment by BrianEnigma** [comment]
This should be complete now, as of https://github.com/PuzzledPint/puzzledpint.com/pull/88
