### ISSUE TITLE
Investigate dreamhost for cheaper hosting

### ISSUE THREAD

**Issue by civrot** [PuzzledPint/puzzledpint.com#63]

**Comment by sparCKL** [comment]
AREN'T WE ALREADY USING DREAMHOST?!?

Domain Name: PUZZLEDPINT.COM
Registry Domain ID: 1574791152_DOMAIN_COM-VRSN
Registrar WHOIS Server: whois.dreamhost.com
Registrar URL: www.dreamhost.com
Updated Date: 2015-11-08T00:28:38.00Z
Creation Date: 2009-11-05T20:54:04.00Z
Registrar Registration Expiration Date: 2016-11-06T05:54:04.00Z
Registrar: DREAMHOST
[...]

**Comment by civrot** [comment]
For the current site, yes.  Beta is currently running on heroku.

**Comment by sparCKL** [comment]
O I C
