### ISSUE TITLE
improve locations display page

### ISSUE THREAD

**Issue by sparCKL** [PuzzledPint/puzzledpint.com#68]
firewall(?) issues prevent some users from seeing the dynamically loaded iframe(?) when they solve the location puzzle. Any way to use a static page and re-generate only when cities add locations?

**Comment by sparCKL** [comment]
This is the error some people see:
"""
Correct!

Find your city below to see where you're going Tuesday night.

Don't forget to bring pens, pencils, scissors, and tape.

No pre-registration is necessary, but please RSVP if there's a link for your city. Just show up at the bar and look for the Puzzled Pint logo.

An error has occured. Please contact GC gamecontrol@puzzledpint.com

"""

**Comment by zyrain** [comment]
http://www.webdesignerdepot.com/2015/11/dynamic-sites-at-static-speed-the-art-of-website-caching/

**Comment by BrianEnigma** [comment]
1. Do we know the underlying reason for this? (Something in the javascript to render the JSON? CORS headers being stripped by a firewall?)

2. Would it be less flaky to have the beta site render the whole thing, then either redirect there or put the pre-rendered content in a frame?
