### ISSUE TITLE
iCal-compatible feed for events

### ISSUE THREAD

**Issue by BrianEnigma** [PuzzledPint/puzzledpint.com#76]
We should be able to publish a simple [iCal format](https://en.wikipedia.org/wiki/ICalendar) feed of any upcoming event(s) stored in the database for both GC and players to consume. This becomes even more useful if we end up putting multiple placeholder events for future months into the database so that people can plan ahead.

**Comment by civrot** [comment]
I dunno. Its the second Tuesday of every month.

**Comment by civrot** [comment]
Oops, didn't mean to close it,

**Comment by BrianEnigma** [comment]
It's the second Tuesday of every month... except for the couple of cases when it isn't. It's a nice-to-have for folks that are too lazy to figure out how to add recurring events to their calendars. Also, gen2 of this feature might add a second calendar feed, with PM duties appropriated backdated from the event date.
