### ISSUE TITLE
Some cities could use a state too

### ISSUE THREAD

**Issue by mcleinman** [PuzzledPint/puzzledpint.com#83]
Washington, DC is rarely just called "Washington" in a list.  And Paris, TX could also use the state.  Create an admin flag for cities that allows the state to be sent to the front end.

**Comment by BrianEnigma** [comment]
Instead of one-offing this with a checkbox/boolean for showing state, how about in addition to the “name” field, we also add a “display_name” field that defaults to the city name? This way, we could localize it for any city/state/country disambiguation.

**Comment by BrianEnigma** [comment]
...or something other than `display_name` because that's already defined as “{parent city name} {hyphen} {city name}” 😀
